[features]
seeds = false

[programs.localnet]
stable_swap = "39rpAgmdTmc5fLXUA9vZw59fz4byzZNok9bH7MFV9RzS"

[programs.devnet]
stable_swap = "39rpAgmdTmc5fLXUA9vZw59fz4byzZNok9bH7MFV9RzS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/coredev0927/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
