[features]
seeds = false
[programs.devnet]
apricot = "4DGj9snmzbMeXJyG5XSzVdywt2dQ4nb4mKRxCAc3X25N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/coredev0927/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
