[features]
seeds = false

[programs.localnet]
swap_router = "HQQC4EbED22P49XiJmMXFLkinHZ1aVEBveZfTSowmJGB"

[programs.devnet]
swap_router = "HQQC4EbED22P49XiJmMXFLkinHZ1aVEBveZfTSowmJGB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/coredev0927/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
