[features]
seeds = false

[programs.localnet]
uniswap = "AwtkxxDuTqg2x1wNU6crTf5rM4vgPrupquqbqLSeegUm"

[programs.devnet]
uniswap = "AwtkxxDuTqg2x1wNU6crTf5rM4vgPrupquqbqLSeegUm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/coredev0927/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
